use ContosoRetailDW
SELECT top  100000

cust.CustomerKey,
cust.FirstName + ' ' + cust.LastName AS [FullName],
cust.Gender,
cust.BirthDate,
cust.DateFirstPurchase,
year(cust.DateFirstPurchase)-year(cust.BirthDate)AS Age,
cust.YearlyIncome,
cust.Occupation,
cust.Education,
cust.MaritalStatus,
cust.TotalChildren,
cust.NumberChildrenAtHome,
cust.HouseOwnerFlag,
cust.NumberCarsOwned,
cust.CustomerType,
dt.FullDateLabel,
dt.CalendarDayOfWeekLabel,
dt.FiscalYear,
dt.FiscalYear,
dt.FiscalHalfYearLabel,
dt.FiscalQuarterLabel,
dt.CalendarMonthLabel,
dt.IsWorkDay,
dt.EuropeSeason,
dt.NorthAmericaSeason,
dt.AsiaSeason,
chln.ChannelName,
sls.SalesKey,
sls.UnitCost,
sls.UnitPrice,
sls.DiscountAmount,
sls.SalesAmount,
sls.SalesAmount-sls.TotalCost AS SalesProfitAmount,
prod.BrandName,
stre.StoreType,
stre.StoreName,
stre.Status,
onln.DiscountAmount AS OnlineDiscountAmount,
onln.UnitCost AS OnlineUnitCost,
onln.UnitPrice AS OnlineUnitPrice,
onln.TotalCost AS OnlineTotalCost,
onln.SalesAmount AS OnlineSalesAmount,
onln.SalesAmount - onln.TotalCost AS OnlineProfit,
promo.PromotionName,
promo.PromotionType,
promo.PromotionCategory,
promo.DiscountPercent AS [PromoDiscout%],
promo.StartDate AS [PromoStartDate],
promo.EndDate AS [PromoEndDate],
DateDiff(month,stre.OpenDate,promo.StartDate)AS [PeriodBeforePromo(months)],
DateDiff(month,promo.StartDate,promo.EndDate) AS [PromoPeriod(months)],
geo.StateprovinceName,
geo.RegionCountryName


From DimCustomer cust
INNER JOIN DimGeography geo ON cust.GeographyKey = geo.GeographyKey
INNER JOIN DimStore stre ON geo.GeographyKey = stre.GeographyKey
INNER JOIN FactSales sls ON stre.StoreKey = sls.StoreKey
INNER JOIN DimChannel chln ON sls.ChannelKey = chln.ChannelKey
INNER JOIN DimPromotion promo ON sls.PromotionKey = promo.PromotionKey
INNER JOIN FactOnlineSales onln ON cust.CustomerKey = onln.CustomerKey
INNER  JOIN DimDate dt ON onln.DateKey = dt.Datekey
LEFT  JOIN DimProduct prod ON sls.ProductKey = prod.ProductKey

WHERE cust.FirstName + ' ' + cust.LastName  is not null

Group by
sls.SalesKey,
cust.CustomerKey,
cust.FirstName + ' ' + cust.LastName,
cust.Gender,
cust.BirthDate,
cust.DateFirstPurchase,
year(cust.DateFirstPurchase)-year(cust.BirthDate),
cust.YearlyIncome,
cust.Occupation,
cust.Education,
cust.MaritalStatus,
cust.TotalChildren,
cust.NumberChildrenAtHome,
cust.HouseOwnerFlag,
cust.NumberCarsOwned,
cust.CustomerType,
dt.FullDateLabel,
dt.CalendarDayOfWeekLabel,
dt.FiscalYear,
dt.FiscalYear,
dt.FiscalHalfYearLabel,
dt.FiscalQuarterLabel,
dt.CalendarMonthLabel,
dt.IsWorkDay,
dt.EuropeSeason,
dt.NorthAmericaSeason,
dt.AsiaSeason,
chln.ChannelName,
sls.UnitCost,
sls.UnitPrice,
sls.DiscountAmount,
sls.SalesAmount,
sls.SalesAmount-sls.TotalCost,
prod.BrandName,
stre.StoreType,
stre.StoreName,
stre.Status,
onln.DiscountAmount,
onln.UnitCost,
onln.UnitPrice ,
onln.TotalCost ,
onln.SalesAmount ,
onln.SalesAmount - onln.TotalCost,
promo.PromotionName,
promo.PromotionType,
promo.PromotionCategory,
promo.DiscountPercent,
promo.StartDate ,
promo.EndDate ,
DateDiff(month,stre.OpenDate,promo.StartDate),
DateDiff(month,promo.StartDate,promo.EndDate) ,
geo.StateprovinceName,
geo.RegionCountryName